<?php

/**
 * @file
 * Autoload includes folder.
 */

$moduleName = basename(dirname(_FILE_));
$pathsToInclude = glob(drupal_get_path('module', $moduleName) . '/hooks/*');

if ($pathsToInclude) {
  foreach ($pathsToInclude as $path) {
    $pathInfo = pathinfo($path);
    $directory = str_replace(drupal_get_path('module', $moduleName), '', $pathInfo['dirname']);
    if (isset($pathInfo['extension'])) {
      module_load_include($pathInfo['extension'], $moduleName, $directory . '/' . $pathInfo['filename']);
    }
  }
}
