# Schema for the configuration files of the connected theme.
connected.settings:
  type: theme_settings
  label: 'connected settings'
  mapping:
    font_size:
      type: integer
      label: Font size
